### ISSUE TITLE
error trying to use spawnCommand link in the example. 

### ISSUE THREAD

**Issue by rlemon** [mmalecki/spawn-command#4]
```
var spawnCommand = require('spawn-command');
var cmd = 'ssh command I need to monitor';
var child = spawnCommand(cmd);
```

produces the following error: 

> var child = spawnCommand(cmd);
>  ................^
> TypeError: object is not a function

I am using a older version of node, 0.8.22 (which is out of my control). Could this be causing my error here?

**Comment by mmalecki** [comment]
Sorry for the extremely late reply here,  i bet you've solved this in the 10 years that passed. Feel free to reopen if you're still seeing this, and are not on 0.8 ;)
