### ISSUE TITLE
 warning:65(node:6564) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

### ISSUE THREAD

**Issue by wangzhiguoengineer** [mmalecki/spawn-command#9]
![image](https://github.com/mmalecki/spawn-command/assets/16033868/e101ea22-c36f-453e-84a7-bb2e80d76f6b)

**Comment by mmalecki** [comment]
Published as 0.0.3 (which I'm not a fan of, just wanted to make sure everyone with more restrictive semver policies gets this change).

**Comment by mmalecki** [comment]
Also, lol, I think I've actually seen this warning on my own terminal, and it slipped my mind that I'm the author of this one

**Comment by glensc** [comment]
every release with 0.x (and so 0.x.y) is major version by semver spec. so you could as well released 1.0.0 to indicate the library is complete.

**Comment by mmalecki** [comment]
That crossed my mind and is likely what I'll end up doing indeed. Thanks @glensc!

**Comment by mmalecki** [comment]
Done!
